Netbankingproject/Netbankingproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('netbankingapp.urls')),
    path('credentials/',include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Netbankingproject/credentials/urls.py
from django.urls import path
from . import views
app_name='credentials'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),

]

Netbankingproject/netbankingapp/urls.py
from django.urls import path
from . import views
app_name='netbankingapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('appform/',views.getdata,name='appform'),
    path('final/',views.final,name='final'),
]

Netbankingproject/credentials/models.py
from django.db import models

# Create your models here.

Netbankingproject/netbankingapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE


# Create your models here.


class department(models.Model):
    departmentname = models.CharField(max_length=100)


class employee(models.Model):
    name = models.CharField(max_length=250)
    dob = models.DateField(blank=True, null=True)
    age = models.IntegerField()
    deptid = models.ForeignKey(department, on_delete=CASCADE)
    empname = models.CharField(max_length=100)
    address = models.CharField(max_length=500, null=True)
    contactno = models.CharField(max_length=20)
    def __str__(self):
        return self.name

Netbankingproject/credentials/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages, auth
import sys
sys.setrecursionlimit(1500)
# Create your views here.
def login (request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return render(request,'apphome.html')
        else:
            messages.info(request,'invalid credentials')
            return render(request, 'login.html')
    return render(request,'login.html')
def register (request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username taken')
                return render(request,'register.html')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();
                return render(request,'login.html')
        else:
            messages.info(request,'password not matching')
            return render(request,'register.html')
    return render(request,'register.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

Netbankingproject/netbankingapp/views.py
from django.shortcuts import render
from .models import department, employee

def getdata(request):
    if request.method=='POST':
        name=request.POST.get('name')
        dob=request.POST.get('dob')
        age=request.POST.get('age')
        appform=employee(name=name,dob=dob,age=age)
        appform.save()
        return render(request,'final.html')
    template_name = 'appform.html'
    deptcontext = department.objects.all()
    empcontext = employee.objects.all()

    return render(request, template_name,{'department': deptcontext,'employee': empcontext } )
def index(request):
    return render(request,'home.html')
def final(request):
    return render(request,'final.html')

Netbankingproject/templates/appform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DropDown</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<header>
    <center>
       <a href="{% url 'netbankingapp:index' %}"><img src="{% static 'img/logo1.png' %}" alt="logimage" width="120px" height="120px"> </a></div>
    </center>
</header>
<center>
<section>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-8 col-md-6 col-lg-6 col-xl-6">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
<h2><b>Application Form</b></h2><br>
              <br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name"><b>Name</b></label>
    <input  size="72" type="text" name="name" placeholder="Enter your name"><br>
    <br>
    <label for="dob"><b>Date Of Birth</b></label>
    <input size="72" type="date" name="dob" placeholder="Enter your DOB">
    <label for="age"><b>Age</b></label>
    <input  size="72" type="number" name="age" placeholder="Enter your age"><br>
    <br>
    <label  for="gender"><b>Gender</b></label>
    <input type="radio" name="gender" value="male"> Male
    <input type="radio" name="gender" value="female"> Female<br>
    <br>
    <label for="ph"><b>Phone Number</b></label>
    <input size="72" type="number" name="ph" placeholder="Enter your phone number"><br>
    <br>
    <label for="email"><b>Email</b></label>
    <input type="email" size="72" name="email" placeholder="Enter your email"><br>
    <br>
    <label for="adress"><b>Adress</b></label><br>
    <input type="text" size="72" name="email" placeholder="Enter your adress"><br>
    <br>

    <label for="district"><b>District</b></label>
    <select name="dept" id="department" class="form-control">
    <option value="0">Select your disrict:</option>
    <option value="1">Ernakulam</option>
    <option value="2">Kozhikde</option>
    <option value="3">Kannur</option>
    <option value="4">Trivandrum</option>
    <option value="5">Thrissur</option>>
            {% for item in department  %}
            <option value="{{ item.id }}">{{ item.departmentname }}</option>
            {% endfor %}
    </select>
    <br>
    <label for="branch"><b>Branch</b></label>
        <select name="emp" id="Employee" class="form-control">
            <option value="0">Select your branch</option>
            <option value="1">Vypin</option>
            <option value="1">kaloor</option>
            <option value="1">Aluva</option>
            <option value="2">Kozhikode</option>
            <option value="2">Vadakara</option>
            <option value="2">Koyilandy</option>
            <option value="3">kannur</option>
            <option value="3">Thalassery</option>
            <option value="3">Payyannur</option>
            <option value="4">Trivandrum</option>
            <option value="4">East Fort</option>
            <option value="4">Nemom</option>
            <option value="5">Thrissur</option>
            <option value="5">Chalakkudy</option>
            <option value="5">Guruvayur</option>
            {% for item in employe  %}
            <option value="{{ item.deptid_id }}">{{ item.empname }}</option>
            {% endfor %}
        </select>
    <br>
   <label for="acc"><b>Account Type</b></label>
        <select name="acc" id="acctype" class="form-control">
            <option value="0">Select your account type</option>
            <option value="1">Savings account</option>
            <option value="2">Current account</option>
            <option value="3">NRI account</option>
        </select><br>
    <label for="mat"><b>Materials Provided</b></label><br>
    <input type="checkbox" id="credit" name="credit" value="0">
    <label for="credit">Credit Card</label><br>
    <input type="checkbox" id="Cheque" name="Cheque" value="1">
    <label for="Cheque">Cheque Book</label><br>
    <input type="checkbox" id="atm" name="atm" value="2">
    <label for="atm">ATM Card</label><br>

    <br>
    <a href="{% url 'netbankingapp:final' %}"><button type="button" class="btn btn-success btn-lg btn-block"><b>Submit</b></button></a><br>
    <a href="{% url 'netbankingapp:index' %}"><button type="button" class="btn btn-danger btn-lg btn-block"><b>Logout</b></button></a>
    <br>
    <br>

</form>
      </div>
      </div>
    </div>
  </div>
  </div>
</section>
</center>
<script>

$(document).ready(function(){

 var department = $("#department");
 var Employee = $("#Employee");
 var $options = Employee.find('option');
 department.on('change',function(){
    Employee.html($options.filter('[value="'+ this.value  +'"]'));
 }).trigger('change');


});
</script>
</body>
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="{% url 'netbankingapp:index' %}">&copy; Your Bank pvt ltd. All rights reserved.</a>
  </div>
  <!-- Copyright -->
</footer>
</html>

Netbankingproject/templates/apphome.html
{% extends 'base.html' %}
{% block body %}
<div class="my_bottom_margin">
    <div class="text-center my_title">
        <p>
            Dear user please click <a href="{% url 'netbankingapp:appform' %}">here</a> to fill the application form and make sure that the informations are valid
        </p>
    </div>
</div>
{% endblock %}

Netbankingproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block body %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

</body>
</html>

Netbankingproject/templates/final.html
{% extends 'base.html' %}
{% block body %}
<div class="my_bottom_margin">
    <div class="text-center my_title">
        <p>
            Application Accepted. Click <a href="{% url 'netbankingapp:index' %}">here</a> to return back to home page
        </p>
    </div>
</div>
{% endblock %}

Netbankingproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">
      &copy; Your Bank pvt ltd. All rights reserved.
  </p>
</div>

Netbankingproject/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'netbankingapp:index' %}"><img src="{% static 'img/logo1.png' %}" alt="logimage" width="120px" height="120px"> </a></div>
    </center>
</header>

Netbankingproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
   home
{% endblock %}
{% block body %}

    <div class="text-center my_title">
        <p>Welcome to Your Bank PVT LTD.</p>
    </div>

<div width="1000" height="500">
        <img class="my_image my_image_padding" src="{% static 'img/banner3.png' %}"  alt="Your Bank" width="500px" height="500px">
</div>
<br>
<div class="my_bottom_margin">
    <center>
    <h1>Your Bank</h1>
    </center>
    <p>bank, an institution that deals in money and its substitutes and provides other money-related services. In its role as a financial intermediary, a bank accepts deposits and makes loans. <a href="credentials/login">Log on</a> to your account for more...</p>
</div>
{% endblock %}

Netbankingproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <form class="form-container" action="{% url 'credentials:login' %}" method="post" >
            {% csrf_token %}
            <h2>Login</h2>
             <div class="form-outline mb-4">
            <label for="username"><b>Username</b></label>
            <input type="text" name="username" placeholder="Enter  your username" required><br>
             </div>
             <div class="form-outline mb-4">
            <label for="password"><b>Password</b></label>
            <input type="password" name="password" placeholder="Enter your password" required><br>
             </div>
            <center>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>

            <a href="{% url 'netbankingapp:index' %}"><button type="button" class="btn btn-danger btn-lg btn-block">Close</button></a>
            </center>
                <hr class="my-4">
            </form>
           </div>
            <center>
    <div>
        <p>If you are not registered yet, register <a href="{% url 'credentials:register' %}">here</a></p>
    </div>
                </center>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Netbankingproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'credentials:logout' %}">Log out</a>
          </li>
        {% else %}
         <li class="nav-item">
            <a class="nav-link " href="{% url 'credentials:register' %}">Register</a>
         </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'credentials:login' %}">Log in</a>
          </li>
        {% endif %}
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branches
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">Kannur</a>
        </div>
      </li>

    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>

Netbankingproject/templates/register.html
{% extends 'base.html' %}
{% block body %}
<section class="vh-100" style="background-color: white;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
<center>
  <h2>Register</h2>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter username"><br>
    <br>
    <input type="password" name="password" placeholder="Enter password"><br>
    <br>
    <input type="password" name="password1" placeholder="confirm password"><br>
    <br>
    <button type="submit"  class="btn btn-success">Register</button>
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</center>
      </div>
      </div>
    </div>
  </div>
  </div>
</section>
{% endblock %}